services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-frontend:latest
    ports:
      - "8080:80"
    environment:
      # Example: pass Vite envs at build time (see below)
      # - VITE_API_BASE=https://api.example.com
    restart: unless-stopped
